dist: trusty
language: java


jdk:
  - openjdk11
  - openjdk8
  # - oraclejdk11
  # - oraclejdk8


env:
  matrix:
    # - TESTOPT="-R:1.9 -A:provided:test:test-runner"
    - TESTOPT="-R:1.10 -A:provided:test:test-runner"
    # - TESTOPT="-R:1.9 -A:provided:test:eastwood"
    - TESTOPT="-R:1.10 -A:provided:test:eastwood"


install:
  - install_script=linux-install-1.10.1.536.sh
  - curl -LO https://download.clojure.org/install/$install_script
  - chmod +x $install_script
  - sudo ./$install_script
  - rm $install_script
  - export PATH=/usr/local/bin:$PATH
  - which gpg
  - which mvn
  - cp .ci/settings.xml $HOME/.m2/


cache:
  directories:
    - $HOME/.m2
    - $HOME/.gitlibs


script: clojure $TESTOPT


jobs:
  include:
    - stage: package
      jdk: openjdk11
      env: TESTOPT=""
      script: clojure -A:provided:test -m user.tools.deps.script.package -r user.java.lang
      before_cache:
        - mvn dependency:get -Dartifact=org.apache.maven.plugins:maven-deploy-plugin:2.8
      after_success:
        - git config --local user.name "ajchemist"
        - git config --local user.email "1694505+aJchemist@users.noreply.github.com"
        - eval $(ssh-agent -s)
        - ssh-add <(openssl aes-256-cbc -K $encrypted_9c3ee05df822_key -iv $encrypted_9c3ee05df822_iv -in .ci/deploy-key.enc -d)
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - git checkout master
        - git add -- pom.xml
        - git commit -m "$(clojure -A:provided:test -m user.apache.maven.script.get-pom-version) [ci skip]"
        - git remote add origin-ssh "git@github.com:ajchemist/user.java.lang"
        - git remote -v
        - git push -v -u origin-ssh master:refs/heads/master
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: master
          jdk: openjdk11
        script: mvn deploy:deploy-file -Dclojars.username="$CLOJARS_USERNAME" -Dclojars.password="$CLOJARS_PASSWORD" -DpomFile="pom.xml" -Dfile="target/package.jar" -Dpackaging=jar -DrepositoryId="clojars" -Durl="https://clojars.org/repo"


notifications:
  slack:
    rooms:
      - secure: "CN8/+VaDM0LMsNniAmvzboYvoFpFXceOP25jYemN7gHmNAqCL86POPBl5jPdyb4IqHiRP8nr/NrZbbQvTtJ45lji7joFwCqCkuqp2gIhZbB44w2WhoIo25vqMdEH+V6EBZkj7xJuiHnMZ3y44xWNArSPFbxecxSZI8TvbKRnK3CU+3SOl7NjSrN0j1n0z5lR/BozKJ8+8hRQK6TyT+X5g32PGxrpZu4rueanUATu59HlhSJ74uYbcddRBttrJrSDir/kU5TaxgVeIzYcwklGMg8jpOvBZIYpxrjisXAYG4OE+cMs9IZVFT9dS2Ddi4k+7FflQbpBmvELdHxMevJ4107evAFqEnSnjEudTi/mxDyg5hVizSFGuLw2UJkZh3FtROfvEIai2RvCLLnQdWQSRGln2oOqeBXh9dOfak/N4AskySo26g5xD1kcCoXJ/8T7u6/2XCLnwZ/UbgUCGcHMhINNvcl4ix+DL8ixUv5+SlVGQ9YwkOLV2L/2pMGs6F4qs0d3cjrOoVSH//KavbYqZBCswylzEBV7fEFpo2H2e2/cb7ncf44S0E5PSeZYtbcwE1rXgq8YymDNAvArSunkUd3GvYd50rK8me0VYAewj1sU6bFEOhRDOCBBN52VZsTrvLmoxYN/1sr0aaZIVwnHT3A1CMRkpC34yIwnU0sW72E="
    on_success: always
    on_failure: always
